[package]
name = "rustpython-mp-testing"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.14"
threadpool = "1.8.1"
clap = "2.33.3"
uuid = { version = "0.8", features = ["serde", "v4"] }